CREATE TABLE "GCG_4552_SALES_ORDER"(
 "ORDER_NO" CHAR(7),
 "RECORD_NO" CHAR(4),
 "PART" CHAR(20),
 "CUSTOMER" CHAR(6),
 "NAME_CUSTOMER" CHAR(30),
 "QTY_ORDERED" DOUBLE,
 "QTY_REQUIRED" DOUBLE,
 "QTY_SCANNED" DOUBLE,
 "FLAG_BOM" CHAR(1),
 "DESCRIPTION" CHAR(30));
